### ISSUE TITLE
A pointer that is always actived

### ISSUE THREAD

**Issue by rauwebieten** [ExtendRealityLtd/Tilia.Indicators.ObjectPointers.Unity#130]
I'm trying to implement a straight object pointer that is "always on".
I only find tutorials/documentation that use a ButtonAction.

I'm new to unity/vrtk, can someone please help me out, steer me into the right direction?
Thanks a lot

**Comment by thestonefox** [comment]
Github issues are for raising bug reports or feature requests.

If you want help with any aspect of vrtk, then ask in the discord channel: https://discord.com/invite/bRNS6hr
