### ISSUE TITLE
 the pointer facade needs a 'Follow Source Origin/Offset

### ISSUE THREAD

**Issue by funkadelic83** [ExtendRealityLtd/Tilia.Indicators.ObjectPointers.Unity#175]
I am following the new YouTube tutorials, and was able to set up a curved pointer and straight pointer just fine. However, once I add a Locomotors.AxisMove.Veritcal-Warp.Horizontal-SnapRotate and hooked it up, it leaves the Curved pointer behind when I move around the scene. So the pointer stays stuck at the origin point without following the player.

When I try hooking the Curved Pointer up to the "RightControllerAlias" in the Tracked Alias  _instead_ of "RightPointer" in the poses prefab, the pointers will follow the the player when I move around the scene properly - but the laser points up at a weird angle that is unnatural.

I have both UnityInputSystem.InputActionMappings.GenericXR and UnityInputSystem.Poses.GenericXR added to the Heirarchy.

I asked in Discord and another user asked me to open this ticket with this info:

The pointer pose returns only the 'relative position of the pointer against the Device tracking origin'
The pointer facade needs a 'Follow Source Origin/Offset' as well

https://user-images.githubusercontent.com/38448260/232967016-0464ccab-a393-4b43-b39c-9f67c12038c8.mp4

**Comment by thestonefox** [comment]
The poses need to be a child of the play area alias.

This is covered in this video at the 3 minute mark:

https://www.youtube.com/watch?v=cguaIZzv-Eg&t=170
