### ISSUE TITLE
Add HowToGuide for limiting Pointer to NavMesh

### ISSUE THREAD

**Issue by extendreality** [ExtendRealityLtd/Tilia.Indicators.ObjectPointers.Unity#70]
Basic guide of how to use the TargetPointValidity and NavMeshRule to limit valid targets to within nav mesh.

**Comment by thestonefox** [comment]
* Based off off Straight Pointer Guide
* Set `Floor` to Static
* Add a `Cube` make static and place on floor somewhere
* Bake navmesh
* Add NavMeshRule to Pointer
* Drag drop NavMeshRule to TargetPointValidity
* Play the scene and notice the pointer is only valid within the navmesh
